// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6YFjNnNmTb2b9I4WPLxrKVVv79jxKSF4',
    appId: '1:782188520007:web:bee6f8533f33c528dfc762',
    messagingSenderId: '782188520007',
    projectId: 'verdex-a44b5',
    authDomain: 'verdex-a44b5.firebaseapp.com',
    storageBucket: 'verdex-a44b5.firebasestorage.app',
    measurementId: 'G-EQXMVE6FWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlJbyXSegjWszJg3IPN6K4c591CROIDsY',
    appId: '1:782188520007:android:bedf616b0c8300f3dfc762',
    messagingSenderId: '782188520007',
    projectId: 'verdex-a44b5',
    storageBucket: 'verdex-a44b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJF9D0UcPgRz5uS7PQqzDq1-jsqgGSTQA',
    appId: '1:782188520007:ios:85780dbb16f4e42adfc762',
    messagingSenderId: '782188520007',
    projectId: 'verdex-a44b5',
    storageBucket: 'verdex-a44b5.firebasestorage.app',
    iosBundleId: 'com.example.verdex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJF9D0UcPgRz5uS7PQqzDq1-jsqgGSTQA',
    appId: '1:782188520007:ios:85780dbb16f4e42adfc762',
    messagingSenderId: '782188520007',
    projectId: 'verdex-a44b5',
    storageBucket: 'verdex-a44b5.firebasestorage.app',
    iosBundleId: 'com.example.verdex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6YFjNnNmTb2b9I4WPLxrKVVv79jxKSF4',
    appId: '1:782188520007:web:fba11a0180fd6eeddfc762',
    messagingSenderId: '782188520007',
    projectId: 'verdex-a44b5',
    authDomain: 'verdex-a44b5.firebaseapp.com',
    storageBucket: 'verdex-a44b5.firebasestorage.app',
    measurementId: 'G-N0XXF4BK5W',
  );
}